DEBUG:flwr:Opened insecure gRPC connection (no certificates were passed)
DEBUG:flwr:ChannelConnectivity.IDLE
DEBUG:flwr:ChannelConnectivity.CONNECTING
DEBUG:flwr:ChannelConnectivity.READY
INFO:flwr:
INFO:flwr:Received: train message e8351954-af85-415a-a6f3-0af9d4a0984f
INFO:test:Client sampled for fit()
INFO:test:['Wi-Fi end: 1719475501.1150153']
INFO:test:['Evaluation phase (wlan0): [sent: 117980, recv: 5357892]']
INFO:test:Computation phase started
DEBUG:flwr:ChannelConnectivity.IDLE
ERROR:flwr:Client raised an exception.
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.10/site-packages/flwr/client/app.py", line 379, in _start_client_internal
    reply_message = client_app(message=message, context=context)
  File "/home/pi/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 98, in __call__
    return self._call(message, context)
  File "/home/pi/.local/lib/python3.10/site-packages/flwr/client/client_app.py", line 81, in ffn
    out_message = handle_legacy_message_from_msgtype(
  File "/home/pi/.local/lib/python3.10/site-packages/flwr/client/message_handler/message_handler.py", line 130, in handle_legacy_message_from_msgtype
    fit_res = maybe_call_fit(
  File "/home/pi/.local/lib/python3.10/site-packages/flwr/client/client.py", line 234, in maybe_call_fit
    return client.fit(fit_ins)
  File "/home/pi/.local/lib/python3.10/site-packages/flwr/client/numpy_client.py", line 238, in _fit
    results = self.numpy_client.fit(parameters, ins.config)  # type: ignore
  File "/home/pi/E2FL/client_dataset.py", line 398, in fit
    train(self.model, trainloader, optimizer, epochs=epochs, device=self.device)
  File "/home/pi/E2FL/client_dataset.py", line 162, in train
    criterion(net(images.to(device)), labels.to(device)).backward()
  File "/home/pi/.local/lib/python3.10/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/home/pi/.local/lib/python3.10/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/pi/.local/lib/python3.10/site-packages/flwr/client/app.py", line 616, in signal_handler
    raise StopIteration from None
StopIteration
DEBUG:flwr:gRPC channel closed
INFO:flwr:Disconnect and shut down
INFO:test:['Wi-Fi end: 1719475797.361074']
INFO:test:['Evaluation phase (wlan0): [sent: 134808, recv: 5363507]']
